services:
  - type: cron
    name: secop-monitor
    schedule: "0 15,20,1 * * *"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: SECOP_APP_TOKEN
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_NAME
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: STEALTH_MODE
        sync: false
